server:
  port:
    8082
    
eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
      
Feign:
  hystrix:
    enabled: true
  circuitBreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxyStreamAllowList: "*"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:file:~/shopping_cart_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
